name: Check Secret Value

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  checkAndPrint:
    runs-on: macos-latest

    steps:
      - name: Check Secret Value
        run: |
          if [ -z "${{ secrets.MY_SECRET }}" ]; then
            echo "Error: MY_SECRET is not set"
            exit 1
          fi
          
      - name: Print Secret Value
        run: echo ${{ secrets.MY_SECRET }}
