name: Swift Package CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Swift
      uses: swift-actions/setup-swift@v1.23.0
      with:
        swift-version: 5.8
      
    - name: Build
      run: swift build -v
  
  test:
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Swift
      uses: swift-actions/setup-swift@v1.23.0
      with:
        swift-version: 5.8
      
    - name: Run tests
      run: swift test -v
